FROM herlo/linchpin:latest
LABEL name="contrainfra/linchpin-executor" \
      maintainer="herlo@redhat.com" \
      version="0.1.0" \
      description="LinchPin executable container running the latest Fedora release"


