FROM herlo/linchpin:CONTAINER_VERSION
LABEL name="contrainfra/linchpin-executor" \
      maintainer="herlo@redhat.com" \
      version="0.1.1" \
      description="LinchPin executable container running the latest Fedora release"


